"""Figures for Resonance_Hypothesis_for_Gradient_Spikes_in_the_LowRank_Kick.md.

Five PNGs into this folder. Every panel is either an exact evaluation of the
leapfrog stability formula, a clearly-labelled synthetic illustration of a
decision rule, or the measured step-87196 table reproduced from the note --
nothing is fit to unpublished data.

  rh_stability_wall.png     -- the mechanism. Panel A: the exact per-kick
                               amplification factor of explicit (leapfrog)
                               integration of a harmonic mode,
                               rho = |a| + sqrt(a^2 - 1) with a = 1 - h^2/2,
                               h = omega*dt: identically 1 below h = 2 and
                               rising steeply above it. Panel B: the same
                               factor compounded through L = 8 layers, log
                               axis, with the measured 897x spike ratio
                               (2539.20 / 2.83) marked and the omega*dt it
                               implies read off the curve.
  rh_threshold_vs_magnitude.png
                            -- why SS33 measured a weak correlation. Panel A:
                               gradient response under a magnitude model
                               (smooth, proportional) vs a threshold model
                               (flat, then a cliff), with SS33's measured
                               +1% to +24% elevation band overlaid. Panel B:
                               synthetic scatter of spike size against
                               sigma_max^2 generated by a pure threshold --
                               deterministic mechanism, weak correlation.
  rh_observed_collapse.png  -- the measured step-87196 ablation (A100,
                               2026-09-13). Panel A: pre-clip gradient norm
                               per arm on a log axis, collapsing ~900x at the
                               first truncation and flat thereafter. Panel B:
                               the same arms' batch perplexity, moving
                               smoothly. The contrast is the observation the
                               note is about.
  rh_sum_alignment.png      -- why discarding the SMALLEST direction of each
                               well is enough. Synthetic: 40 rank-4 factors
                               (K = 8 wells x n_c = 5 channels) in d = 384,
                               summed into L = sum_k g_k B_k B_k^T;
                               lambda_max(L) recomputed as every factor is
                               truncated together, for independent vs
                               partially-aligned wells.
  rh_falsification_map.png  -- the D1 decision from SS4: what the matched-noise
                               control settles, and which programme branch
                               each outcome opens.

Run:  python3 _make_resonance_hypothesis_figs.py
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, Rectangle

plt.rcParams.update({
    "font.size": 11,
    "axes.titlesize": 12,
    "axes.titleweight": "bold",
    "figure.dpi": 150,
})

GREEN = "#22C55E"
BLUE = "#3B82F6"
RED = "#EF4444"
PURPLE = "#8B5CF6"
GREY = "#9CA3AF"
DARK = "#111827"
AMBER = "#F59E0B"

N_LAYERS = 8

# Measured, step 87196 (A100, 2026-09-13) -- see the note's SS1 table.
ARMS = ["untruncated", "rank 4", "rank 3", "rank 2", "rank 1"]
GRAD = [2539.20, 2539.20, 2.83, 4.35, 2.87]
PPL = [76.6, 76.6, 79.9, 87.2, 105.7]
SPIKE_RATIO = GRAD[0] / GRAD[2]          # ~897x


def rho(h):
    """Exact per-application amplification of leapfrog on a harmonic mode.

    x_{n+1} - (2 - h^2) x_n + x_{n-1} = 0 has roots of modulus 1 while
    h = omega*dt < 2 (pure oscillation, marginally stable) and a real root
    of modulus > 1 beyond it.
    """
    h = np.asarray(h, dtype=float)
    a = 1.0 - h ** 2 / 2.0
    out = np.ones_like(h)
    over = np.abs(a) > 1.0
    aa = np.abs(a[over])
    out[over] = aa + np.sqrt(aa ** 2 - 1.0)
    return out


def h_for_total_gain(gain, n_layers=N_LAYERS):
    """Invert rho(h)^n = gain analytically."""
    r = gain ** (1.0 / n_layers)
    a = (r + 1.0 / r) / 2.0                      # |a|
    return float(np.sqrt(2.0 * (a + 1.0)))       # h from a = h^2/2 - 1


# ---------------------------------------------------------------- figure 1
def fig_stability_wall():
    fig, (axA, axB) = plt.subplots(1, 2, figsize=(11.6, 4.3))
    h = np.linspace(0, 3.0, 1200)
    r = rho(h)

    axA.axvspan(0, 2, color=GREEN, alpha=0.10)
    axA.axvspan(2, 3, color=RED, alpha=0.10)
    axA.plot(h, r, color=DARK, lw=2.4)
    axA.axvline(2, color=RED, ls="--", lw=1.8)
    axA.axhline(1, color=GREY, ls=":", lw=1.2)
    axA.text(1.0, 2.2, "stable\n(pure oscillation)", ha="center",
             color="#15803D", fontsize=10, fontweight="bold")
    axA.text(2.55, 2.2, "amplifying", ha="center", color="#B91C1C",
             fontsize=10, fontweight="bold")
    axA.text(2.02, 3.5, r"$\omega\Delta t = 2$", color=RED, fontsize=11,
             fontweight="bold")
    axA.set_xlabel(r"$\omega \Delta t$")
    axA.set_ylabel(r"amplification per kick  $\rho$")
    axA.set_title("A. The wall is a threshold, not a slope")
    axA.set_xlim(0, 3)
    axA.set_ylim(0, 4)

    gain = rho(h) ** N_LAYERS
    axB.axvspan(0, 2, color=GREEN, alpha=0.10)
    axB.axvspan(2, 3, color=RED, alpha=0.10)
    axB.semilogy(h, gain, color=PURPLE, lw=2.4)
    axB.axvline(2, color=RED, ls="--", lw=1.8)

    h_obs = h_for_total_gain(SPIKE_RATIO)
    axB.axhline(SPIKE_RATIO, color=AMBER, ls="--", lw=1.6)
    axB.plot([h_obs], [SPIKE_RATIO], "o", color=AMBER, ms=9,
             markeredgecolor=DARK, zorder=5)
    axB.annotate(
        f"measured spike ratio {SPIKE_RATIO:.0f}x\n"
        rf"$\Rightarrow \omega\Delta t \approx {h_obs:.2f}$"
        f"\n({100 * (h_obs / 2 - 1):.0f}% past the wall)",
        xy=(h_obs, SPIKE_RATIO), xytext=(2.30, 6.0),
        fontsize=9.2, color=DARK,
        arrowprops=dict(arrowstyle="->", color=AMBER, lw=1.8))
    axB.set_xlabel(r"$\omega \Delta t$")
    axB.set_ylabel(rf"total gain through $L={N_LAYERS}$ layers  $\rho^{{{N_LAYERS}}}$")
    axB.set_title("B. Compounding turns a small overshoot into a spike")
    axB.set_xlim(0, 3)
    axB.set_ylim(0.5, 1e5)

    fig.suptitle("Explicit integration of the low-rank channel: an on/off "
                 "instability", fontsize=12.5, fontweight="bold")
    fig.tight_layout(rect=(0, 0, 1, 0.93))
    fig.savefig("rh_stability_wall.png", bbox_inches="tight")
    plt.close(fig)
    return h_obs


# ---------------------------------------------------------------- figure 2
def fig_threshold_vs_magnitude():
    fig, (axA, axB) = plt.subplots(1, 2, figsize=(11.6, 4.3))
    rel = np.linspace(-0.10, 0.45, 600)          # relative change in sigma_max^2

    # Magnitude model: gradient proportional to curvature.
    mag = 1.0 + rel
    # Threshold model: baseline until the wall is crossed, then compounding.
    #   omega*dt scales as sqrt(sigma_max^2), baseline placed just under 2.
    base_h = 1.90
    h_of = base_h * np.sqrt(1.0 + rel)
    thr = rho(h_of) ** N_LAYERS

    axA.axvspan(1.0, 24.0, color=BLUE, alpha=0.13)
    axA.text(12.5, 2.2e3, "SS33 measured band\n+1% to +24%", ha="center",
             fontsize=9.2, color="#1D4ED8", fontweight="bold")
    axA.semilogy(100 * rel, mag, color=GREY, lw=2.4,
                 label="magnitude model (gradient $\\propto$ curvature)")
    axA.semilogy(100 * rel, thr, color=PURPLE, lw=2.4,
                 label="threshold model (this note)")
    axA.axhline(1, color=GREY, ls=":", lw=1.2)
    axA.set_xlabel(r"change in $\sigma_{\max}(B_k)^2$  (%)")
    axA.set_ylabel("gradient norm, relative to healthy")
    axA.set_title("A. Same input range, two very different responses")
    axA.legend(fontsize=8.8, loc="lower right")
    axA.set_ylim(0.5, 1e4)

    # Panel B: a pure threshold generates weak correlation.
    #
    # omega*dt is set by lambda_max of the SUMMED operator
    # L = sum_k g_k B_k B_k^T, so any one well's sigma_max^2 is only one of
    # its inputs -- occupancies g_k and cross-well alignment move it at
    # least as much. That is modelled here as `other`, and it is why a
    # deterministic threshold still leaves sigma_max^2 a poor predictor.
    rng = np.random.default_rng(20260913)
    n = 260
    s = rng.normal(1.0, 0.11, n).clip(0.75, 1.45)      # sigma_max^2, relative
    other = rng.normal(1.0, 0.090, n)                   # g_k, alignment
    hh = base_h * np.sqrt(s) * other
    g = rho(hh) ** N_LAYERS * rng.lognormal(0, 0.18, n)
    spiked = g > 5
    axB.scatter(100 * (s[~spiked] - 1), g[~spiked], s=17, color=GREY,
                alpha=0.65, label="ordinary step")
    axB.scatter(100 * (s[spiked] - 1), g[spiked], s=26, color=RED,
                alpha=0.85, label="spike")
    axB.set_yscale("log")
    axB.set_ylim(0.3, 3e7)
    axB.set_xlabel(r"change in $\sigma_{\max}(B_k)^2$  (%)")
    axB.set_ylabel("gradient norm, relative to healthy")
    corr = np.corrcoef(s, np.log(g))[0, 1]
    elev = 100 * (np.median(s[spiked]) / np.median(s[~spiked]) - 1.0)
    axB.set_title(f"B. A deterministic threshold, yet r = {corr:.2f}")
    axB.legend(fontsize=8.8, loc="upper left")
    axB.text(0.97, 0.97,
             f"median $\\sigma_{{\\max}}^2$ at spikes is only "
             f"+{elev:.0f}% higher\n"
             "— the same order SS33 measured (+1% to +24%)",
             transform=axB.transAxes, ha="right", va="top", fontsize=9,
             color=DARK,
             bbox=dict(boxstyle="round,pad=0.4", fc="#FEF3C7", ec=AMBER))
    print(f"panel B: {100 * spiked.mean():.0f}% spiked, r = {corr:.2f}, spike median elevation = +{elev:.1f}%")

    fig.suptitle("Why a threshold mechanism looks like a weak lever under a "
                 "magnitude test", fontsize=12.5, fontweight="bold")
    fig.tight_layout(rect=(0, 0, 1, 0.93))
    fig.savefig("rh_threshold_vs_magnitude.png", bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------- figure 3
def fig_observed_collapse():
    fig, (axA, axB) = plt.subplots(1, 2, figsize=(11.6, 4.3))
    x = np.arange(len(ARMS))
    colors = [DARK, GREY, BLUE, BLUE, BLUE]

    axA.bar(x, GRAD, color=colors, alpha=0.88, edgecolor=DARK, linewidth=0.6)
    axA.set_yscale("log")
    axA.set_xticks(x)
    axA.set_xticklabels(ARMS, rotation=18, ha="right")
    axA.set_ylabel("pre-clip gradient norm")
    axA.set_title("A. Gradient: a cliff, then a floor")
    axA.set_ylim(1, 1e4)
    for xi, v in zip(x, GRAD):
        axA.text(xi, v * 1.35, f"{v:,.2f}", ha="center", fontsize=8.6,
                 color=DARK)
    axA.annotate("", xy=(1.94, 6.2), xytext=(1.06, 1900),
                 arrowprops=dict(arrowstyle="->", color=RED, lw=2.2))
    axA.text(1.34, 90, f"{SPIKE_RATIO:.0f}x", color=RED, fontsize=12,
             fontweight="bold", ha="center")

    axB.bar(x, PPL, color=colors, alpha=0.88, edgecolor=DARK, linewidth=0.6)
    axB.set_xticks(x)
    axB.set_xticklabels(ARMS, rotation=18, ha="right")
    axB.set_ylabel("batch perplexity")
    axB.set_title("B. Loss: smooth and ordered")
    axB.set_ylim(0, 125)
    for xi, v, g in zip(x, PPL, [0, 0, 4.3, 13.8, 38.0]):
        lab = f"{v:.1f}" + (f"\n+{g:.1f}%" if g else "")
        axB.text(xi, v + 3, lab, ha="center", fontsize=8.6, color=DARK)

    fig.suptitle("Measured at step 87196: the spike is annihilated for a "
                 "4.3% loss cost", fontsize=12.5, fontweight="bold")
    fig.tight_layout(rect=(0, 0, 1, 0.93))
    fig.savefig("rh_observed_collapse.png", bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------- figure 4
def fig_sum_alignment():
    """lambda_max of the SUMMED operator as every well is truncated together.

    The point of the figure is the coherent-tail case. A direction can be
    individually negligible in every single well -- the smallest singular
    direction of each B_k -- and still dominate lambda_max of the sum, if
    the 40 factors all place it in the same place. Truncation removes that
    direction from all 40 at once, so the collective mode disappears even
    though each well barely changed.

    Synthetic, shaped like the deployed configuration: d = 384,
    K = 8 wells x n_c = 5 channels = 40 rank-4 factors.
    """
    rng = np.random.default_rng(7)
    d, n_fac, r = 384, 40, 4
    shared = rng.standard_normal(d)
    shared /= np.linalg.norm(shared)
    c_tail = 0.35                       # individually the SMALLEST column

    def lam_max(rank, coherent):
        tot = np.zeros((d, d))
        for _ in range(n_fac):
            B = rng.standard_normal((d, r)) / np.sqrt(d)
            if coherent:
                B[:, -1] = c_tail * shared
            U, S, Vt = np.linalg.svd(B, full_matrices=False)
            S = S.copy()
            S[rank:] = 0.0
            Bt = U @ np.diag(S) @ Vt
            tot += Bt @ Bt.T
        return np.linalg.eigvalsh(tot)[-1]

    ranks = [4, 3, 2, 1]
    rng = np.random.default_rng(7)
    indep = np.array([lam_max(k, False) for k in ranks])
    rng = np.random.default_rng(7)
    coh = np.array([lam_max(k, True) for k in ranks])
    indep_n, coh_n = indep / indep[0], coh / coh[0]

    fig, ax = plt.subplots(figsize=(8.4, 4.9))
    xs = np.arange(len(ranks))
    ax.plot(xs, coh_n, "o-", color=PURPLE, lw=2.4, ms=9,
            label="coherent tail (same weak direction in every well)")
    ax.plot(xs, indep_n, "s--", color=GREY, lw=2.0, ms=8,
            label="independent wells")

    wall = 0.5 * (coh_n[0] + coh_n[1])           # between rank 4 and rank 3
    ax.axhspan(wall, 1.15, color=RED, alpha=0.10)
    ax.axhline(wall, color=RED, ls="--", lw=1.8)
    ax.text(2.92, wall + 0.02, r"$\omega\Delta t = 2$", color=RED,
            fontsize=10.5, fontweight="bold", ha="right")
    ax.text(2.92, 1.08, "amplifying", color="#B91C1C", fontsize=10,
            fontweight="bold", ha="right")

    ax.annotate(f"{100 * (1 - coh_n[1]):.0f}% drop from removing\n"
                "the weakest direction alone",
                xy=(1.0, coh_n[1]), xytext=(1.25, 0.72), fontsize=9.2,
                color=DARK,
                arrowprops=dict(arrowstyle="->", color=PURPLE, lw=1.8))

    ax.set_xticks(xs)
    ax.set_xticklabels([f"rank {k}" for k in ranks])
    ax.set_xlabel("every well truncated to")
    ax.set_ylabel(r"$\lambda_{\max}(L)$, relative to untruncated")
    ax.set_title("A direction too weak to matter in any one well can still\n"
                 "dominate the summed operator")
    ax.legend(fontsize=9.0, loc="lower right")
    ax.set_ylim(0.0, 1.15)
    ax.text(0.02, 0.03,
            "synthetic: $d=384$, 40 rank-4 factors.\nWall position illustrative.",
            transform=ax.transAxes, fontsize=8.3, color=GREY)

    fig.tight_layout()
    fig.savefig("rh_sum_alignment.png", bbox_inches="tight")
    plt.close(fig)
    print(f"coherent tail: lambda_max drops {100 * (1 - coh_n[1]):.0f}% at "
          f"rank 3; independent drops {100 * (1 - indep_n[1]):.0f}%")


# ---------------------------------------------------------------- figure 5
def fig_falsification_map():
    fig, ax = plt.subplots(figsize=(9.8, 5.2))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 6.4)
    ax.axis("off")

    def box(x, y, w, h, text, fc, ec, fs=9.4, weight="normal"):
        ax.add_patch(FancyBboxPatch((x, y), w, h,
                                    boxstyle="round,pad=0.10",
                                    fc=fc, ec=ec, lw=1.8))
        ax.text(x + w / 2, y + h / 2, text, ha="center", va="center",
                fontsize=fs, color=DARK, fontweight=weight)

    box(3.1, 5.25, 3.8, 0.85,
        "Observed: any truncation\ncollapses the gradient ~900x",
        "#EFF6FF", BLUE, fs=10, weight="bold")

    box(3.1, 3.85, 3.8, 0.85,
        "D1  matched-noise control\nsame energy, rank preserved",
        "#FEF3C7", AMBER, fs=10, weight="bold")
    ax.annotate("", xy=(5.0, 4.70), xytext=(5.0, 5.25),
                arrowprops=dict(arrowstyle="->", color=DARK, lw=2.0))

    box(0.25, 2.05, 4.2, 1.35,
        "spike ALSO dies\n\nknife-edge: any change of this\n"
        "size defuses it. Truncation says\nnothing about rank or direction.",
        "#FEE2E2", RED)
    box(5.55, 2.05, 4.2, 1.35,
        "spike SURVIVES\n\nthe discarded directions were\n"
        "specifically load-bearing;\nthe rank reading stands.",
        "#DCFCE7", GREEN)
    ax.annotate("", xy=(2.35, 3.40), xytext=(4.2, 3.85),
                arrowprops=dict(arrowstyle="->", color=RED, lw=2.0))
    ax.annotate("", xy=(7.65, 3.40), xytext=(5.8, 3.85),
                arrowprops=dict(arrowstyle="->", color=GREEN, lw=2.0))

    box(0.25, 0.25, 4.2, 1.45,
        "still test the mechanism:\n"
        "D2 measure $\\omega\\Delta t$ directly\n"
        "D3 sweep $B \\to \\alpha B$ for a knee\n"
        "D5 halve $\\Delta t$   D6 exact arm",
        "#F3F4F6", GREY, fs=9.0)
    box(5.55, 0.25, 4.2, 1.45,
        "rank question is answerable:\n"
        "re-run at a healthy checkpoint\n"
        "(step 87196 is an outlier\n"
        "by construction)",
        "#F3F4F6", GREY, fs=9.0)
    ax.annotate("", xy=(2.35, 1.70), xytext=(2.35, 2.05),
                arrowprops=dict(arrowstyle="->", color=GREY, lw=1.8))
    ax.annotate("", xy=(7.65, 1.70), xytext=(7.65, 2.05),
                arrowprops=dict(arrowstyle="->", color=GREY, lw=1.8))

    ax.set_title("What the D1 control settles", fontsize=12.5,
                 fontweight="bold")
    fig.tight_layout()
    fig.savefig("rh_falsification_map.png", bbox_inches="tight")
    plt.close(fig)


if __name__ == "__main__":
    h_obs = fig_stability_wall()
    fig_threshold_vs_magnitude()
    fig_observed_collapse()
    fig_sum_alignment()
    fig_falsification_map()
    print(f"measured spike ratio      : {SPIKE_RATIO:.1f}x")
    print(f"implied per-layer rho     : {SPIKE_RATIO ** (1 / N_LAYERS):.3f}")
    print(f"implied omega*dt at spike : {h_obs:.3f} "
          f"({100 * (h_obs / 2 - 1):.1f}% past the wall)")
    print("wrote 5 figures")
